routers/HomeTabNavigator.js, screens/AuthenticationScreen.js
- done handle countdown send back
=> #1 - handle coundown send back

components/buttons/TextInputAccount.js, components/buttons/TextInputPassword.js, screens/LoginScreen.js, screens/RegisterScreen.js
=> #4 fix design login and register

components/inputs/TextInputPrimary.js, routers/HomeTabNavigator.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/ChatListScreen.js, screens/home/ProfileScreen.js
- create navigation
- change name component InputPrimary -> TextInputPrimary
- create Profile Screen
=> #12 - create navigation & fix bug's Phuong

README.md, components/Menu/MenuItem.js, components/Menu/Tooltip.js, components/searchBar/SearchBar.js, package-lock.json, package.json, screens/AuthenticationScreen.js, screens/home/ChatListScreen.js
- error platform android -> duplicate icon and margin top about 20
=> #12 - create menu search bar

README.md, components/Menu/MenuItem.js, components/Menu/Tooltip.js, package-lock.json, package.json, screens/home/ChatListScreen.js
=> #12 - done menu bar

components/headers/TopBar/TopBar.js, screens/messages/MessageScreen.js
=> #12 - update code change but forgot commit - sorry

components/headers/Header.js, components/headers/TopBar/TopBar.js, package-lock.json, screens/messages/MessageScreen.js
=> #12 - fix issue keyboard android

components/inputs/TextInputPrimary.js, screens/LoginScreen.js, screens/RegisterScreen.js
=> #10 add user name

screens/home/ProfileScreen.js
=> #11 add logout

App.js, components/ChatItem/index.js, components/Messages/MessageInputBox/index.js, components/searchBar/Menu/MenuItem.js, components/searchBar/Menu/Tooltip.js, components/searchBar/SearchItem.js, components/searchBar/index.js, package-lock.json, package.json, redux/selector.js, redux/slice/MessageSlice.js, redux/store.js, screens/messages/MessageScreen.js
- use redux send data
- remove `ToolTip` in Menu
- create tooltip delete to ChatItem
=> #29 - send data by redux - custom tooltip

components/inputs/TextInputPrimary.js, screens/LoginScreen.js
- add keyBoard prop to input
- create utils
=> add keyBoard prop to input

App.js, README.md, components/Messages/MessageInputBox/index.js, components/searchBar/SearchItem.js, components/searchBar/index.js, package-lock.json, package.json, redux/selector.js, redux/slice/MessageSlice.js, redux/slice/filterSlice.js, redux/slice/usersSlice.js, redux/store.js, routers/RootStackNavigator.js, screens/home/ChatListScreen.js
- create search item
- create userSlice
- handle find user then input name
=> #37 - init search user

package-lock.json, package.json, routers/RootStackNavigator.js, screens/AuthenticationScreen.js, screens/LoginScreen.js, screens/home/ProfileScreen.js, utils/APIManager.js, utils/asyncStorage.js, utils/firebase.js, utils/users_api.js
=> #27 login with token

App.js, babel.config.js, config.js, package-lock.json, package.json, redux/selector.js, redux/slice/userInfoSlice.js, redux/slice/usersSlice.js, redux/store.js, screens/LoginScreen.js, screens/home/ChatListScreen.js
- create slice
- change method get token login
=>  #37 - fetch data user for search method

redux/slice/filterSlice.js, redux/slice/userInfoSlice.js, routers/RootStackNavigator.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/ProfileScreen.js
- custom get token
- handle keyboard ios
- doing handle loading get token & logout
=>  #27 - hanlde login display

components/SearchBar/index.js, redux/slice/userInfoSlice.js, screens/LoginScreen.js, screens/home/ChatListScreen.js
- fix loading logout
- move action fetch user to searchBar
=> #28 fix logout

components/SearchBar/SearchItem.js, components/SearchBar/index.js, hooks/useDebounce.js, redux/selector.js, redux/slice/friendSlice.js, redux/store.js, screens/home/ChatListScreen.js
- find user by phone
- find friends by userName
- create hook useDeboune
=> #37 - search success user

components/ChatItem/index.js, components/SearchBar/SearchItem.js, redux/selector.js, redux/slice/conversationSlice.js, redux/slice/userInfoSlice.js, redux/store.js, screens/LoginScreen.js, screens/home/ChatListScreen.js, screens/home/HomeScreen.js, screens/home/ProfileScreen.js, screens/personal/PersonalScreen.js
=> #42 load conversation

screens/home/PhoneBookScreen.js
=> #54 load friend list

components/SearchBar/index.js, config.js, redux/selector.js, redux/slice/conversationSlice.js, redux/slice/friendSlice.js, redux/slice/userInfoSlice.js, redux/slice/usersSlice.js, routers/RootStackNavigator.js, screens/LoadingScreen.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/PhoneBookScreen.js, screens/home/ProfileScreen.js, screens/home/messages/MessageScreen.js, screens/home/personal/PersonalScreen.js, utils/asyncStorage.js
- create loading screen
- move all fetch data first to loading screen
=> #56 - create loading screen

components/ChatItem/index.js, components/Messages/MessageItem/ActionMessage/index.js, components/Messages/MessageItem/ImageMessage/index.js, components/Messages/MessageItem/index.js, redux/selector.js, redux/slice/conversationSlice.js, redux/slice/messageSlice.js, screens/LoadingScreen.js, screens/home/ChatListScreen.js, screens/home/messages/MessageScreen.js, screens/home/personal/PersonalScreen.js, utils/asyncStorage.js
- load messsages by conversation id from chat screen & personal screen
=> #56 - load success messages

components/ChatItem/index.js, config.js, redux/selector.js, redux/slice/messageSlice.js, redux/slice/userInfoSlice.js, screens/LoadingScreen.js, screens/LoginScreen.js, screens/home/messages/MessageScreen.js, utils/asyncStorage.js
- send - receiver through socket -> OK
=> #56 - send message socket success

app.json, components/Messages/MessageInputBox/index.js, components/Messages/MessageItem/ImageMessage/index.js, package-lock.json, package.json, redux/slice/messageSlice.js, screens/LoadingScreen.js
=> #29 - add message image success

redux/selector.js, redux/slice/conversationSlice.js, redux/slice/messageSlice.js
- sort conversation
- catching error by alert
=> #29 - sort conversation by time

redux/selector.js, screens/home/phonebook/FriendScreen.js, screens/home/phonebook/GroupChatScreen.js, screens/home/phonebook/NewFriendScreen.js
=> #75 success load list group

components/ChatItem/index.js, config.js, redux/selector.js, redux/slice/friendSlice.js, redux/slice/messageSlice.js, routers/RootStackNavigator.js, screens/LoadingScreen.js, screens/addFriends/AddFriendScreen.js
- replace path socket in config.js
- comment console.log
=> #29 - replace path socket

components/Messages/MessageInputBox/index.js, redux/selector.js, redux/slice/messageSlice.js, screens/home/messages/MessageScreen.js
- handle loading message by redux
=> #29 - handle loading message

components/SearchBar/index.js, redux/selector.js, redux/slice/friendSlice.js, routers/RootStackNavigator.js, screens/addFriends/AddFriendScreen.js, screens/home/ChatListScreen.js, screens/home/phonebook/NewFriendScreen.js, screens/home/search/SearchScreen.js
- fix friend request
- block search
- still error logic
=> #60 fix friend request

app.json, components/SearchBar/SearchItem.js, components/SearchBar/index.js, redux/selector.js, redux/slice/friendSlice.js, screens/LoadingScreen.js, screens/addFriends/AddFriendScreen.js, screens/home/ChatListScreen.js, screens/home/phonebook/NewFriendScreen.js, screens/home/phonebook/SyncPhoneBook.js, screens/home/search/SearchScreen.js
=> #60 success full friends request

screens/AuthenticationScreen.js, utils/firebase.js
=> #87 fix register with firebase

components/Inputs/TextInputPrimary.js, config.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/forgotPass/ConfirmPhoneNumber.js
- success all feature related to login
=> #94 final all feature related to login

package-lock.json, package.json, redux/slice/userInfoSlice.js, screens/AuthenticationScreen.js, screens/LoadingScreen.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/infoSelf/InfoSelf.js, screens/home/personal/PersonalScreen.js
- fix logic info
- err send back otp
=> #92 fix logic info

components/Messages/MessageInputBox/index.js, components/Messages/MessageItem/FileMessage/index.js, components/Messages/MessageItem/index.js, components/SearchBar/Menu/TooltipCustom.js, redux/selector.js, screens/LoadingScreen.js, screens/home/messages/MessageScreen.js, utils/filePathConfig.js
- create file pathConfig
- block send image in send file
=> #104 - fix methods

screens/LoadingScreen.js, screens/RegisterScreen.js
=> #87 fix register

config.js, screens/home/phonebook/SyncPhoneBook.js
=> #104 - handle sync phone book

components/SearchBar/SearchItem.js, redux/selector.js, screens/home/messages/MessageScreen.js, screens/home/personal/PersonalScreen.js, screens/home/phonebook/GroupChatScreen.js
=> #112 fix click info personal screen

README.md, components/Messages/MessageItem/FileMessage/index.js, components/Messages/MessageItem/index.js, config.js, package-lock.json, package.json, routers/RootStackNavigator.js, screens/home/ChatListScreen.js, screens/home/messages/MessageScreen.js, screens/home/messages/ViewFileScreen.js
- use `npm i react-native-webview`
- create ViewFileScreen
=> #85 - handle view message file

components/Messages/MessageItem/index.js, config.js, package-lock.json, package.json, redux/slice/conversationSlice.js, screens/home/detailChat/DetailChat.js, screens/home/groupChat/NewGroupChat.js, screens/home/infoSelf/InfoSelf.js, screens/home/personal/PersonalScreen.js, screens/home/phonebook/FriendScreen.js, screens/home/phonebook/GroupChatScreen.js, screens/home/search/SearchScreen.js
- create group with friend and no friend
=> #60 success create group

components/ChatItem/index.js, components/Messages/MessageItem/FileMessage/index.js, components/Messages/TopBar/TopBar.js, components/SearchBar/SearchItem.js, components/SearchBar/index.js, config.js, redux/selector.js, redux/slice/conversationSlice.js, routers/RootStackNavigator.js, screens/home/ChatListScreen.js, screens/home/detailChat/DetailChat.js, screens/home/detailChat/detailGroup/AllMembers.js, screens/home/groupChat/NewGroupChat.js, screens/home/messages/MessageScreen.js
- add members
- remove meber
- out group
- change name group
=> #121 handle detail group

components/SearchBar/SearchItem.js, config.js, redux/slice/conversationSlice.js, screens/LoadingScreen.js, screens/home/detailChat/DetailChat.js, screens/home/groupChat/NewGroupChat.js
=> #121 update avatar group

.gitignore, components/Messages/MessageItem/ActionMessage/index.js, config.js, package-lock.json, package.json, redux/slice/conversationSlice.js, redux/slice/messageSlice.js, redux/slice/userInfoSlice.js, screens/LoadingScreen.js, screens/home/detailChat/DetailChat.js
- add members to group
- change name group
- change avatar group
=> #119 - handle group with socket

redux/slice/conversationSlice.js
=> #119 - handle block user in group

config.js, redux/slice/userInfoSlice.js, screens/LoadingScreen.js, screens/home/ProfileScreen.js
- fix logout have info last user login
=> #104 - fix logout reset info

components/ChatItem/index.js, components/Messages/MessageInputBox/index.js, components/Messages/TopBar/TopBar.js, components/SearchBar/SearchItem.js, redux/selector.js, redux/slice/conversationSlice.js, screens/home/detailChat/DetailChat.js, screens/home/detailChat/detailGroup/AllMembers.js, screens/home/messages/MessageScreen.js
=> #128 block member success

components/SearchBar/SearchItem.js, redux/selector.js, redux/slice/friendSlice.js, screens/LoadingScreen.js, screens/home/HomeScreen.js
- succes remove friend request
=> #135 success remove friend request

components/ChatItem/index.js, components/Messages/MessageInputBox/index.js, components/Messages/MessageItem/ActionMessage/index.js, components/Messages/TopBar/TopBar.js, components/SearchBar/SearchItem.js, config.js, redux/slice/conversationSlice.js, redux/slice/friendSlice.js, redux/slice/messageSlice.js, redux/slice/userInfoSlice.js, screens/AuthenticationScreen.js, screens/LoadingScreen.js, screens/RegisterScreen.js, screens/home/ChatListScreen.js, screens/home/PhoneBookScreen.js, screens/home/detailChat/DetailChat.js, screens/home/groupChat/NewGroupChat.js, screens/home/phonebook/NewFriendScreen.js, screens/home/phonebook/SyncPhoneBook.js
- recall request friend
- cancel request friend
=> #119 - handle friend request

components/Messages/MessageItem/index.js, components/Messages/TopBar/TopBar.js, components/SearchBar/Menu/TooltipCustom.js, config.js, redux/slice/conversationSlice.js, redux/slice/friendSlice.js, redux/slice/messageSlice.js, redux/slice/userInfoSlice.js, redux/slice/usersSlice.js, routers/RootStackNavigator.js, screens/AuthenticationScreen.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/forgotPass/ConfirmPhoneNumber.js, screens/home/messages/ReportScreen.js, screens/home/phonebook/FriendScreen.js
- create ui
- handle method
- Mr.Phuong must change LINK_API_V4 -> LINK_API in env
=> #138 - create ui + handle method

components/SearchBar/SearchItem.js, config.js, redux/slice/friendSlice.js, screens/LoadingScreen.js, screens/home/messages/MessageScreen.js, screens/home/phonebook/NewFriendScreen.js
- fix remove friend request wil update back friend request
=> #135 fix bug back friend request

components/SearchBar/SearchItem.js
=> #135 fix send request more user

components/ChatItem/index.js, components/Messages/MessageItem/index.js, components/SearchBar/Menu/MenuItem.js, components/SearchBar/Menu/TooltipCustom.js, package-lock.json, package.json, redux/selector.js, redux/slice/conversationSlice.js, redux/slice/filterSlice.js, redux/slice/friendSlice.js, redux/slice/usersSlice.js, screens/home/ChatListScreen.js, screens/home/groupChat/NewGroupChat.js, screens/home/messages/ReportScreen.js, screens/home/phonebook/FriendScreen.js
- delete conversation
- open form move message
=> #142 delete conversation

components/ChatItem/index.js, components/Messages/MessageItem/index.js, components/Messages/TopBar/TopBar.js, config.js, redux/selector.js, redux/slice/friendSlice.js, redux/slice/messageSlice.js, redux/slice/userInfoSlice.js, redux/slice/usersSlice.js, screens/home/PhoneBookScreen.js, screens/home/groupChat/NewGroupChat.js, screens/home/phonebook/FriendScreen.js
- delete friend
- count friend request
- move message
=> #144 - handle method with socket

redux/slice/userInfoSlice.js, screens/LoadingScreen.js, screens/home/ProfileScreen.js
- check status lock account -> move login
- check status warning -> show message
=> #138 - handle check status after report

redux/slice/userInfoSlice.js, routers/RootStackNavigator.js, screens/LoginScreen.js, screens/RegisterScreen.js, screens/home/forgotPass/ConfirmPhoneNumber.js, screens/home/forgotPass/ReplacePassWord.js, screens/home/infoSelf/InfoSelf.js, screens/home/personal/PersonalScreen.js, screens/home/policy/PolicyScreen.js, styles/LoginStyles.js
- fix notify err
- add new screen policy
- check name update info
- forgot pass auto login
=> #146 add new policy

components/ChatItem/index.js, components/SearchBar/SearchItem.js, redux/selector.js, redux/slice/conversationSlice.js, screens/home/detailChat/DetailChat.js, screens/home/phonebook/FriendScreen.js
- fix click user in phone book
- add block one user
- add delete conversation in detail chat
=> #146 add block and remove conversation

redux/selector.js, redux/slice/conversationSlice.js, screens/home/ChatListScreen.js
=> #146 fix click send chat user

redux/slice/conversationSlice.js, screens/home/ChatListScreen.js, screens/home/detailChat/DetailChat.js
=> #146 fix send chat

screens/RegisterScreen.js, screens/home/forgotPass/ReplacePassWord.js
=> #146 fix register

config.js, redux/selector.js, redux/slice/conversationSlice.js, screens/RegisterScreen.js, screens/home/forgotPass/ReplacePassWord.js
- fix regexPass
- fix recall message with socket
=> fix register

redux/selector.js
- check conversation exist -> search
=> fix search group

components/Messages/MessageInputBox/index.js, redux/selector.js, redux/slice/conversationSlice.js, screens/home/detailChat/DetailChat.js, screens/home/phonebook/FriendScreen.js
=> #146 fix block member

components/Messages/MessageInputBox/index.js, redux/slice/conversationSlice.js, screens/home/detailChat/DetailChat.js
=> #167 fix report
